Ext.define('Regardz.model.property.YieldCalendar', {
    extend: 'Ext.data.Model',
    fields: ['WeekNo',
    'WeekDayNo',
    'SecPrevYearDate',
    'PrevYearDate',
    'CurrentDate',
    'IsHoliday',
    'HolidayName',
    'SecYearSlot1IsExemption',
    'SecYearSlot2IsExemption',
    'SecYearSlot3IsExemption',
    'PrevYearSlot1IsExemption',
    'PrevYearSlot2IsExemption',
    'PrevYearSlot3IsExemption',
    'CurrentYearSlot1IsExemption',
    'CurrentYearSlot2IsExemption',
    'CurrentYearSlot3IsExemption',
    'SecPrevYearSlot1Bar',
    'SecPrevYearSlot2Bar',
    'SecPrevYearSlot3Bar',
    'PrevYearSlot1Bar',
    'PrevYearSlot2Bar',
    'PrevYearSlot3Bar',
    'CurrentYearSlot1Bar',
    'CurrentYearSlot2Bar',
    'CurrentYearSlot3Bar',
    'CurrentFullDate',
    'PrevYearFullDate',
    'SecPrevYearFullDate']
});
