Ext.define('Regardz.model.company.Booking', {
    extend: 'Ext.data.Model',
    fields: ['BookingDate',
             'Status',
             'ReservationId',
             'CompanyId',
             'IndividualId', 
             'BookingName',
             'BookingId',
             'BookingTrackingId',
             'StepNumber',
            'PropertyId',
            'MeetingTypeId',
            'StatusId',
            'FromTime',
            'ToTime',
            'NoOfPeople',
            'DoNotMove',
            'WishListRank',
            'DecisionDate',
            'ContactOnLocation',
            'PaymentMethod',
            'ExtraOptionsOnLocation',
            'IsPurchaseOrderNotApplicable',
            'IsPurchaseOrderWillBeGivenLater',
            'PurchaseOrderNumber',
            'CreatedDate',
            'CreatedBy',
            'UpdatedDate',
            'UpdatedBy',
            'IsFollowLater',
            'IsTrainerIncluded',
            'ContractID',
            'FromTime',
            'ToTime',
            'NoOfPeople',
            'IndividualName',
            'Email',
            'Phone',
            'BusinessTypeId',
            'BookingNumber',
            'IsDisable'
            ]
});

 